package yamllint

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The effective.txt goldens next to each fixture were generated by resolving
// the same .yamllint through ansible-lint's own load_yamllint_config (see
// docs/design/static-yaml-and-var-naming.md), so they pin agreement with
// upstream's merge semantics, not just with this implementation.
func TestLoadMatchesAnsibleLintResolution(t *testing.T) {
	dirs, err := filepath.Glob(filepath.Join("testdata", "config", "*"))
	if err != nil || len(dirs) == 0 {
		t.Fatalf("no config fixtures: %v", err)
	}
	for _, dir := range dirs {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			golden, err := os.ReadFile(filepath.Join(dir, "effective.txt"))
			if err != nil {
				t.Fatal(err)
			}
			cfg, _, err := Load(dir)
			if err != nil {
				t.Fatalf("Load: %v", err)
			}
			if got := cfg.Describe(); got != string(golden) {
				t.Errorf("effective config diverges from ansible-lint's\ngot:\n%s\nwant:\n%s", got, golden)
			}
		})
	}
}

func TestLoadWithoutConfigUsesAnsibleLintDefaults(t *testing.T) {
	cfg, warnings, err := Load(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if len(warnings) != 0 {
		t.Errorf("clean directory produced warnings: %v", warnings)
	}
	if cfg.Describe() != AnsibleLintDefaults().Describe() {
		t.Error("a directory with no config must resolve to ansible-lint's defaults")
	}
}

// A repository config is found under each of the three names, in order.
func TestLoadSearchOrder(t *testing.T) {
	for _, name := range configNames {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			write(t, filepath.Join(dir, name), "---\nrules:\n  truthy: disable\n")
			cfg, _, err := Load(dir)
			if err != nil {
				t.Fatal(err)
			}
			if cfg.Enabled("truthy") {
				t.Errorf("%s was not read", name)
			}
		})
	}
	// .yamllint wins over the other two when several exist.
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".yamllint"), "---\nrules:\n  truthy: disable\n")
	write(t, filepath.Join(dir, ".yamllint.yml"), "---\nrules:\n  line-length: disable\n")
	cfg, _, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Enabled("truthy") || !cfg.Enabled("line-length") {
		t.Error("the first name in the search order must win outright")
	}
}

// Rules accept `disable`, `enable` and a plain `false`; yamllint rewrites the
// first two and its validation reads the third as disabled.
func TestLoadDisableForms(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".yamllint"),
		"---\nrules:\n  truthy: disable\n  line-length: false\n  document-start: enable\n")
	cfg, _, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if cfg.Enabled("truthy") || cfg.Enabled("line-length") {
		t.Error("disable and false must both switch a rule off")
	}
	if !cfg.Enabled("document-start") {
		t.Error("enable must switch a rule on over ansible-lint's disable")
	}
	// A rule switched on with no options must still reach the checks with a
	// complete option set.
	if !cfg.optBool("document-start", "present") {
		t.Error("an enabled rule's options were not filled from the defaults")
	}
}

func TestLoadRejectsBadConfig(t *testing.T) {
	cases := map[string]string{
		"unknown rule":   "---\nrules:\n  no-such-rule: enable\n",
		"unknown option": "---\nrules:\n  line-length:\n    maximum: 10\n",
		"bad level":      "---\nrules:\n  line-length:\n    level: fatal\n",
		"bad shorthand":  "---\nrules:\n  line-length: sometimes\n",
	}
	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			write(t, filepath.Join(dir, ".yamllint"), content)
			if _, _, err := Load(dir); err == nil {
				t.Error("want an error, got none")
			}
		})
	}
}

// Limits the operator must know about are reported rather than swallowed.
//
// `ignore` used to be one of them and is no longer (issue 0006): the patterns
// are applied now, so warning about them would be false. This test pins both
// halves, because a warning that outlives the limitation it describes is worse
// than no warning at all.
func TestLoadWarns(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".yamllint"),
		"---\nignore: |\n  *.generated.yml\nrules:\n  quoted-strings: enable\n")
	cfg, warnings, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	joined := strings.Join(warnings, "\n")
	if !strings.Contains(joined, "quoted-strings") {
		t.Errorf("enabling an unimplemented rule must warn, got %v", warnings)
	}
	if strings.Contains(joined, "ignore") {
		t.Errorf("ignore patterns are applied now, so they must not warn, got %v", warnings)
	}
	if cfg.ForFile("roles/x/vars/main.generated.yml") != nil {
		t.Error("a file the ignore patterns match must yield no yaml config")
	}
	if cfg.ForFile("roles/x/vars/main.yml") == nil {
		t.Error("a file the ignore patterns do not match must still be linted")
	}
}

// `extends: default` reinstates yamllint's stock answer for every rule the
// file does not mention, which is how a repository config silently undoes
// ansible-lint's own overrides.
func TestExtendsDefaultReinstatesYamllintPolicy(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".yamllint"), "---\nextends: default\n")
	cfg, _, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !cfg.Enabled("document-start") {
		t.Error("extends: default must put document-start back, ansible-lint disables it")
	}
	if got := cfg.optInt("line-length", "max"); got != 80 {
		t.Errorf("line-length max = %d, want yamllint's 80 rather than ansible-lint's 160", got)
	}
}

// Touching one option of a rule resets its siblings to yamllint's stock
// values, because upstream completes a parsed config before layering it.
func TestPartialRuleOverrideResetsSiblings(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, ".yamllint"),
		"---\nrules:\n  comments:\n    require-starting-space: false\n")
	cfg, _, err := Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if got := cfg.optInt("comments", "min-spaces-from-content"); got != 2 {
		t.Errorf("min-spaces-from-content = %d, want yamllint's 2: ansible-lint's 1 is discarded", got)
	}
}

// write takes testing.TB rather than *testing.T so the fuzz target can plant
// its fixtures with it too.
func write(tb testing.TB, path, content string) {
	tb.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		tb.Fatal(err)
	}
}
